name: DiscordConnector
version: '${project.version}'
main: de.tamion.minecraft.MCMain
authors: [ Tamion ]
api-version: '1.13'
description: Uses JDA to combine Minecraft and Discord
load: STARTUP
commands:
  setbottoken:
  setmcsyntax:
  setdcsyntax:
  setguildid:
  setjoinsyntax:
  setleavesyntax:
  setstartsyntax:
  setstopsyntax: