name: DCChat
version: '${project.version}'
main: de.tamion.mc.DCChatMC
api-version: 1.19
authors: [ Tamion ]
description: Uses JDA to combine Minecraft and Discord chat
commands:
  setbottoken:
  setmcsyntax:
  setdcsyntax:
  setguildid:
  setchannelid:
  restartbot: